/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YBar: typeof import('./../src/autoImport/components/YBar/index.vue')['default']
    YButton: typeof import('./../src/autoImport/components/YButton/index.vue')['default']
    YButtonGroup: typeof import('./../src/autoImport/components/YButtonGroup/index.vue')['default']
    YContainer: typeof import('./../src/autoImport/components/YContainer/index.vue')['default']
    YContextmenu: typeof import('./../src/autoImport/components/YContextmenu/index.vue')['default']
    YDictLabel: typeof import('./../src/autoImport/components/YDictLabel/index.vue')['default']
    YForm: typeof import('./../src/autoImport/components/YForm/index.vue')['default']
    YFormCascaderItem: typeof import('./../src/autoImport/components/YForm/CascaderItem/index.vue')['default']
    YFormCheckboxItem: typeof import('./../src/autoImport/components/YForm/CheckboxItem/index.vue')['default']
    YFormDateItem: typeof import('./../src/autoImport/components/YForm/DateItem/index.vue')['default']
    YFormDateRangeItem: typeof import('./../src/autoImport/components/YForm/DateRangeItem/index.vue')['default']
    YFormField: typeof import('./../src/autoImport/components/YForm/Field/index.vue')['default']
    YFormInputItem: typeof import('./../src/autoImport/components/YForm/InputItem/index.vue')['default']
    YFormItem: typeof import('./../src/autoImport/components/YForm/Item/index.vue')['default']
    YFormNumberItem: typeof import('./../src/autoImport/components/YForm/NumberItem/index.vue')['default']
    YFormNumberRangeItem: typeof import('./../src/autoImport/components/YForm/NumberRangeItem/index.vue')['default']
    YFormPasswordItem: typeof import('./../src/autoImport/components/YForm/PasswordItem/index.vue')['default']
    YFormRadioItem: typeof import('./../src/autoImport/components/YForm/RadioItem/index.vue')['default']
    YFormSelectItem: typeof import('./../src/autoImport/components/YForm/SelectItem/index.vue')['default']
    YFormSliderItem: typeof import('./../src/autoImport/components/YForm/SliderItem/index.vue')['default']
    YFormSlotItem: typeof import('./../src/autoImport/components/YForm/SlotItem/index.vue')['default']
    YFormSwitchItem: typeof import('./../src/autoImport/components/YForm/SwitchItem/index.vue')['default']
    YFormTextareaItem: typeof import('./../src/autoImport/components/YForm/TextareaItem/index.vue')['default']
    YFormTimeItem: typeof import('./../src/autoImport/components/YForm/TimeItem/index.vue')['default']
    YFormTimeRangeItem: typeof import('./../src/autoImport/components/YForm/TimeRangeItem/index.vue')['default']
    YFormTreeSelectItem: typeof import('./../src/autoImport/components/YForm/TreeSelectItem/index.vue')['default']
    YHelp: typeof import('./../src/autoImport/components/YHelp/index.vue')['default']
    YIcon: typeof import('./../src/autoImport/components/YIcon/index.vue')['default']
    YPageTable: typeof import('./../src/autoImport/components/YPageTable/index.vue')['default']
    YRouteTab: typeof import('./../src/autoImport/components/YRouteTab/index.vue')['default']
    YSearch: typeof import('./../src/autoImport/components/YSearch/index.vue')['default']
    YTable: typeof import('./../src/autoImport/components/YTable/index.vue')['default']
    YTableColumnItem: typeof import('./../src/autoImport/components/YTable/ColumnItem/index.vue')['default']
    YTableToolBar: typeof import('./../src/autoImport/components/YTable/ToolBar/index.vue')['default']
  }
}
